# Generated by Django 5.0.9 on 2025-10-16 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, verbose_name='申請番号')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='申請者名')),
                ('approver_name', models.CharField(max_length=100, verbose_name='承認者名')),
                ('application_date', models.CharField(max_length=10, verbose_name='申請日')),
                ('approval_date', models.CharField(max_length=10, verbose_name='承認日')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='価格')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBNコード')),
                ('title', models.CharField(max_length=255, verbose_name='書籍名')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='著者')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='出版社')),
                ('published_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='出版日')),
                ('description', models.TextField(blank=True, null=True, verbose_name='書籍概要')),
                ('thumbnail_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='書影URL')),
                ('status', models.CharField(choices=[('ordered', '購入中'), ('available', '本棚保管中'), ('rented', '貸出中'), ('other', 'その他')], default='ordered', max_length=10, verbose_name='ステータス')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='保管場所')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '書籍',
                'verbose_name_plural': '書籍',
                'db_table': 'books',
                'indexes': [models.Index(fields=['isbn'], name='idx_isbn'), models.Index(fields=['status'], name='idx_status'), models.Index(fields=['application_number'], name='idx_application_number')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='申請番号')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBNコード')),
                ('error_type', models.CharField(max_length=50, verbose_name='エラー種別')),
                ('error_message', models.TextField(verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='発生日時')),
            ],
            options={
                'verbose_name': 'エラーログ',
                'verbose_name_plural': 'エラーログ',
                'db_table': 'error_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='idx_created_at'), models.Index(fields=['application_number'], name='idx_error_application_number')],
            },
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=100, verbose_name='貸出人名')),
                ('rental_date', models.DateField(verbose_name='貸出日')),
                ('expected_return_date', models.DateField(verbose_name='返却予定日')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='実際の返却日')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_history', to='books.book', verbose_name='書籍')),
            ],
            options={
                'verbose_name': '貸出履歴',
                'verbose_name_plural': '貸出履歴',
                'db_table': 'rental_history',
                'ordering': ['-rental_date'],
                'indexes': [models.Index(fields=['book'], name='idx_book_id'), models.Index(fields=['borrower_name'], name='idx_borrower_name'), models.Index(fields=['rental_date'], name='idx_rental_date')],
            },
        ),
    ]
