# Generated by Django 5.0.9 on 2025-10-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='書籍名'),
        ),
    ]
