# Generated by Django 5.0.9 on 2025-10-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, verbose_name='ISBNコード'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBNコード'),
        ),
    ]
