version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: book_management_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-book_management}
      MYSQL_USER: ${DB_USER:-bookadmin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 10s

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: book_management_app
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../app:/app
      - ../logs:/var/log/book-management
      - ../credentials:/app/credentials
    ports:
      - "8001:8000"
    env_file:
      - ../credentials/.env
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  mysql_data:

